# Generated by Django 3.1.3 on 2020-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='player',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
