# Generated by Django 3.1.3 on 2020-11-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power4', '0002_auto_20201113_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='power4.game'),
            preserve_default=False,
        ),
    ]
