# Generated by Django 3.1.3 on 2020-11-19 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power4', '0004_auto_20201119_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_id',
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
