# Generated by Django 3.1.3 on 2020-11-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power4', '0005_auto_20201119_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dot',
        ),
        migrations.DeleteModel(
            name='VerticalAxis',
        ),
    ]
